### ISSUE TITLE
ReferenceError: qrcode is not defined

### ISSUE THREAD

**Issue by derrend** [dwa012/html5-qrcode#24]
Hello,

I am importing the html5-qrcode.min.js file directly from github while I develop my app and am following readme instructions as accurately as possible but am still getting a 'not defined error'. Please help.

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://raw.githubusercontent.com/dwa012/html5-qrcode/master/lib/html5-qrcode.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#reader').html5_qrcode(function(data){
                    console.log('it works');
                },
                function(error){
                    $('#read_error').html(error);
                }, function(videoError){
                    $('#vid_error').html(videoError);
                }
            );
        });
    </script>

Please can you help me undetstand what is wrong with this code?
Thanks :)

UPDATE:
importing the html5-qrcode.min.js file from the example website fixed the problem but I am still unable to activate the camera in chrome, firefox is working fine.

    <script src="https://raw.githubusercontent.com/dwa012/html5-qrcode/master/lib/html5-qrcode.min.js"></script>

Chrome works on the example website though so there must be something different which I am not realising :/

Why is the html5-qrcode.min.js file that the example site uses different from the file in the git repo?

**Comment by derrend** [comment]
update,
importing the html5-qrcode.min.js file from the example website fixed the problem but I am still unable to activate the camera in chrome, firefox is working fine.

    <script src="https://raw.githubusercontent.com/dwa012/html5-qrcode/master/lib/html5-qrcode.min.js"></script>

**Comment by OACDesigns** [comment]
do you know how to use Grunt? Perhaps try re-building the minified version. I think the one used on the website is actually an older version.

**Comment by derrend** [comment]
Ah, no I've never used grunt before, I'll do my research and try again. I will let the thread know if I'm successful :) Thanks

**Comment by jrevillini** [comment]
I think there's a missing instruction in the readme. Mine worked after I also included the other file in the lib folder like so
`<script src="html5-qrcode-master/lib/jsqrcode-combined.min.js"></script>
    <script src="html5-qrcode-master/lib/html5-qrcode.min.js"></script>`

**Comment by derrend** [comment]
What does 'building' using grunt do? I've looked on youtube and all it seems to do is minify the script but javascript is all source code any way so do I still need to do that?

**Comment by jrevillini** [comment]
I haven't used grunt but it would let you take a script that had, say, 1000 optional animations and build a minified version that only included the 10 that you actually need for your site. I'm not sure what it would do for this thing since there is virtually no configuration.

I wouldn't bother with building with grunt in this case. I really think there's just a missing piece of the docs which I figured out by looking at the demo.

**Comment by derrend** [comment]
@jrevillini now I understand what grunt does, thank you for that :)
I will do as you suggest and inform the thread of my progress. Thanks again

**Comment by OACDesigns** [comment]
Grunt can do a lot of things, from combining and reducing the size of your javascript files (a process called minification), to compilind scss files or compressing images. It's a task runner and your `gruntfile` is where you decide what happens when you do a build.
In this project if you look at the grunt file you'll see that it is indeed just minifying javascript files. it combines all 17 of the `jsqrcode` files into a single file and then creates a minified version which is significantly reduced in filesize. It also creates a minified version of the `html5-qrcode.js` file. The result is that you now only need to include two significantly reduced files in your project, instead of 18 bloated files with unneeded comments, long variable/function names, white space, etc.

I would certainly suggest looking into using Grunt, or Gulp which is another task runner.

**Comment by OACDesigns** [comment]
checkout the `Development` section in the README.md, it goes through the process of doing your own build.

**Comment by derrend** [comment]
@jrevillini I took your advice and incorporated the <script src="html5-qrcode-master/lib/jsqrcode-combined.min.js"> tag but to no avail. (I am importing it directly from github like so <script src="https://raw.githubusercontent.com/dwa012/html5-qrcode/master/lib/jsqrcode-combined.min.js"></script>)

It works fine in firefox but not in chrome. I have pasted the error output from the chrome java console below. If anyone can see the problem please let me know, Thanks guys :)

Refused to execute script from 'https://raw.githubusercontent.com/dwa012/html5-qrcode/master/lib/html5-qrcode.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'https://raw.githubusercontent.com/dwa012/html5-qrcode/master/lib/jsqrcode-combined.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
localhost/:86 Uncaught TypeError: $(...).html5_qrcode is not a function

**Comment by derrend** [comment]
Solved it - https://code.google.com/p/chromium/issues/detail?id=180007

Turns out javascript doesn't execute in chrome when served from github due to the headers.

Quote: "they (Github) don't actually want folks serving files from raw.github.org, which is why they serve resources with the 'nosniff' header."

I imported the code directly into my html page and it worked like a charm. Thank you everyone for your help :)

**Comment by miagendaescolar** [comment]
"jrevillini" solve for me.

**Comment by antelove19** [comment]
**raw.githubusercontent.com** replace with **cdn.jsdelivr.net/gh/**
https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github/60108140#60108140
